theme: minima
title: Life's good
author: servanso
email: servanso@github.org
description: > # this means to ignore newlines until "baseurl:"
  Don't come here this is for training purposes.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  servanso # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
